// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package e2ELanguageSelectApi

import (
    "github.com/apimatic/go-core-runtime/https"
)

// createAuthenticationFromConfig returns a map of auth interfaces that provides authentications for API calls.
func createAuthenticationFromConfig(config Configuration) map[string]https.AuthInterface {
    return map[string]https.AuthInterface {
        "OAuth2": config.AuthorizationCodeAuthCredentials(),
    }
}
