// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package e2ELanguageSelectApi

import (
    "context"
    "e2ELanguageSelectApi/models"
    "encoding/base64"
    "errors"
    "github.com/apimatic/go-core-runtime/https"
    "net/http"
    "net/url"
    "time"
)

// AuthorizationCodeAuthCredentials represents the credentials required for `OAuth2` authentication.
type AuthorizationCodeAuthCredentials struct {
    oAuthClientId     string
    oAuthClientSecret string
    oAuthRedirectUri  string
    oAuthToken        models.OAuthToken
    oAuthScopes       []models.OAuthScope
}

// NewAuthorizationCodeAuthCredentials creates a new instance of AuthorizationCodeAuthCredentials with provided parameters.
func NewAuthorizationCodeAuthCredentials(
    oAuthClientId string,
    oAuthClientSecret string,
    oAuthRedirectUri string) AuthorizationCodeAuthCredentials {
    return AuthorizationCodeAuthCredentials {
        oAuthClientId: oAuthClientId,
        oAuthClientSecret: oAuthClientSecret,
        oAuthRedirectUri: oAuthRedirectUri,
    }
}

// WithOAuthClientId sets oAuthClientId in AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) WithOAuthClientId(oAuthClientId string) AuthorizationCodeAuthCredentials {
    a.oAuthClientId = oAuthClientId
    return a
}

// WithOAuthClientSecret sets oAuthClientSecret in AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) WithOAuthClientSecret(oAuthClientSecret string) AuthorizationCodeAuthCredentials {
    a.oAuthClientSecret = oAuthClientSecret
    return a
}

// WithOAuthRedirectUri sets oAuthRedirectUri in AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) WithOAuthRedirectUri(oAuthRedirectUri string) AuthorizationCodeAuthCredentials {
    a.oAuthRedirectUri = oAuthRedirectUri
    return a
}

// WithOAuthToken sets oAuthToken in AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) WithOAuthToken(oAuthToken models.OAuthToken) AuthorizationCodeAuthCredentials {
    a.oAuthToken = oAuthToken
    return a
}

// WithOAuthScopes sets oAuthScopes in AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) WithOAuthScopes(oAuthScopes []models.OAuthScope) AuthorizationCodeAuthCredentials {
    a.oAuthScopes = oAuthScopes
    return a
}

// OAuthClientId returns the oAuthClientId associated with the AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) OAuthClientId() string {
    return a.oAuthClientId
}

// OAuthClientSecret returns the oAuthClientSecret associated with the AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) OAuthClientSecret() string {
    return a.oAuthClientSecret
}

// OAuthRedirectUri returns the oAuthRedirectUri associated with the AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) OAuthRedirectUri() string {
    return a.oAuthRedirectUri
}

// OAuthToken returns the oAuthToken associated with the AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) OAuthToken() models.OAuthToken {
    return a.oAuthToken
}

// OAuthScopes returns the oAuthScopes associated with the AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) OAuthScopes() []models.OAuthScope {
    return a.oAuthScopes
}

// Validate function returns validation error associated with the AuthorizationCodeAuthCredentials.
func (a AuthorizationCodeAuthCredentials) Validate() error {
    if a.oAuthClientId == "" || a.oAuthClientSecret == "" || a.oAuthRedirectUri == "" {
        return errors.New("OAuth2 : missing auth credentials -> OAuthClientId && OAuthClientSecret && OAuthRedirectUri.")
    }
    if !a.isTokenValid() {
    return errors.New("OAuth2 : Client is not authorized. An OAuth token is needed to make API calls.")
}
     if a.isTokenExpired() {
    return errors.New("OAuth2 : OAuth token is expired. A valid token is needed to make API calls.")
}
    return nil
}

// Authenticator function returns HttpInterceptor function that provides authentication for API calls.
func (a AuthorizationCodeAuthCredentials) Authenticator() https.HttpInterceptor {
    return func(req *http.Request,
        next https.HttpCallExecutor,
    ) https.HttpContext {
            req.Header.Set(https.AUTHORIZATION_HEADER, "Bearer "+ a.OAuthToken().AccessToken)
        return next(req)
    }
}

// isTokenValid checks if the provided OAuthToken is valid.
func (a AuthorizationCodeAuthCredentials) isTokenValid() bool {
    return a.OAuthToken().AccessToken != ""
}

// isTokenExpired checks if the provided OAuthToken is expired based on the expiry timestamp.
func (a AuthorizationCodeAuthCredentials) isTokenExpired() bool {
    return *a.OAuthToken().Expiry <= int64(time.Now().Second())
}

// AuthorizationCodeAuthManager is a manager responsible for handling authorization related operations.
type AuthorizationCodeAuthManager struct {
    authorizationCodeAuthCredentials AuthorizationCodeAuthCredentials
    oAuthAuthorizationController     OAuthAuthorizationController
    configuration                    Configuration
}

// newAuthorizationCodeAuthManager creates a new instance of AuthorizationCodeAuthManager with the given authorizationCodeAuthCredentials and OAuthAuthorizationController.
func newAuthorizationCodeAuthManager(
    authorizationCodeAuthCredentials AuthorizationCodeAuthCredentials,
    oAuthAuthorizationController OAuthAuthorizationController,
    configuration Configuration) *AuthorizationCodeAuthManager {
    authorizationCodeAuthManager := &AuthorizationCodeAuthManager{
        authorizationCodeAuthCredentials: authorizationCodeAuthCredentials,
        oAuthAuthorizationController: oAuthAuthorizationController,
        configuration: configuration,
    }
    
    return authorizationCodeAuthManager
}

// FetchToken fetches the token. It makes a request to the OAuthAuthorizationController
// to obtain the token and returns the token and any error occurred during the request.
func (a *AuthorizationCodeAuthManager) FetchToken(
    ctx context.Context,
    authCode string) (
    models.OAuthToken,
    error) {
    authorization := a.getEncodedString()
    redirectUri := a.authorizationCodeAuthCredentials.OAuthRedirectUri()
    requestTokenInput := RequestTokenInput {
        Authorization: authorization,
        Code: authCode,
        RedirectUri: redirectUri,
    }
    result, err := a.oAuthAuthorizationController.RequestToken(ctx, requestTokenInput, nil)
    if result.Data.ExpiresIn != nil && *result.Data.ExpiresIn != 0 {
        result.Data.Expiry = models.ToPointer(int64(time.Now().Second() + int(*result.Data.ExpiresIn)))
    }
    
    return result.Data, err
}

// getEncodedString encodes the provided credentials (OAuthClientId and OAuthClientSecret) to a Basic Auth string.
func (a *AuthorizationCodeAuthManager) getEncodedString() string {
    return "Basic " + base64.StdEncoding.EncodeToString([]byte(a.authorizationCodeAuthCredentials.OAuthClientId() + ":" + a.authorizationCodeAuthCredentials.OAuthClientSecret()))
}

// BuildAuthorizationURL creates an authorization URL for users to be redirected.
func (a *AuthorizationCodeAuthManager) BuildAuthorizationUrl(state *string) string {
    req := http.Request{}
    url, err := url.Parse(getBaseUri(Server("default"), a.configuration) + "/authorize")
    if err != nil {
        return ""
    }
    req.URL = url
    https.AddQuery(&req, "response_type", "code")
    https.AddQuery(&req, "client_id", a.authorizationCodeAuthCredentials.OAuthClientId())
    https.AddQuery(&req, "redirect_uri", a.authorizationCodeAuthCredentials.OAuthRedirectUri())
    https.AddQuery(&req, "scope", a.getStringScopes())
    if state != nil {
        https.AddQuery(&req, "state", *state)
    }
    return req.URL.String()
}

// RefreshToken refreshes the OAuthToken using the provided refresh token.
func (a *AuthorizationCodeAuthManager) RefreshToken(ctx context.Context) (
    models.OAuthToken,
    error) {
    if !a.authorizationCodeAuthCredentials.isTokenValid() {
        return models.OAuthToken{}, errors.New("OAuth2 : Client is not authorized. An OAuth token is needed to make API calls.")
    }
    authorization := a.getEncodedString()
    refreshToken := ""
    if token := a.authorizationCodeAuthCredentials.OAuthToken().RefreshToken; token != nil {
        refreshToken = *token
    }
    scope := a.getStringScopes()
    if refreshToken != "" {
        return models.OAuthToken{}, errors.New("OAuth2 : Refresh token is invalid. A valid refresh token is needed to make API calls.")
    }
    refreshTokenInput := RefreshTokenInput {
        Authorization: authorization,
        RefreshToken: refreshToken,
        Scope: &scope,
    }
    result, err := a.oAuthAuthorizationController.RefreshToken(ctx, refreshTokenInput, nil)
    
    if result.Data.ExpiresIn != nil && *result.Data.ExpiresIn != 0 {
        result.Data.Expiry = models.ToPointer(int64(time.Now().Second() + int(*result.Data.ExpiresIn)))
    }
    
    return result.Data, err
}

// getStringScopes concatenate the provided slice of oAuthScopes Enum to string.
func (a *AuthorizationCodeAuthManager) getStringScopes() string {
    var oAuthScopes string
    for i, scope := range a.authorizationCodeAuthCredentials.OAuthScopes() {
        if i == 0 {
            oAuthScopes = string(scope)
        } else {
            oAuthScopes = oAuthScopes + " " + string(scope)
        }
    }
    return oAuthScopes
}

// OAuthTokenIsExpired checks the expiry of OAuth Token.
func (a *AuthorizationCodeAuthManager) OAuthTokenIsExpired() bool {
    return a.authorizationCodeAuthCredentials.isTokenExpired()
}
