// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package e2ELanguageSelectApi

import (
    "os"
)

// ConfigurationOptions represents a function type that can be used to apply options to the Configuration struct.
type ConfigurationOptions func(*Configuration)

// Configuration holds configuration settings.
type Configuration struct {
    environment                      Environment
    httpConfiguration                HttpConfiguration
    authorizationCodeAuthCredentials AuthorizationCodeAuthCredentials
    loggerConfiguration              LoggerConfiguration
}

// newConfiguration creates a new Configuration with the provided options.
func newConfiguration(options ...ConfigurationOptions) Configuration {
    config := Configuration{}
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// cloneWithOptions provides configuration with the provided options.
func (config Configuration) cloneWithOptions(options ...ConfigurationOptions) Configuration {
    for _, option := range options {
        option(&config)
    }
    return config
}

// WithEnvironment is an option that sets the Environment in the Configuration.
func WithEnvironment(environment Environment) ConfigurationOptions {
    return func(c *Configuration) {
        c.environment = environment
    }
}

// WithHttpConfiguration is an option that sets the HttpConfiguration in the Configuration.
func WithHttpConfiguration(httpConfiguration HttpConfiguration) ConfigurationOptions {
    return func(c *Configuration) {
        c.httpConfiguration = httpConfiguration
    }
}

// WithAuthorizationCodeAuthCredentials is an option that sets the AuthorizationCodeAuthCredentials in the Configuration.
func WithAuthorizationCodeAuthCredentials(authorizationCodeAuthCredentials AuthorizationCodeAuthCredentials) ConfigurationOptions {
    return func(c *Configuration) {
        c.authorizationCodeAuthCredentials = authorizationCodeAuthCredentials
    }
}

// WithLoggerConfiguration is an option that sets the LoggerConfiguration in the Configuration.
func WithLoggerConfiguration(options ...LoggerOptions) ConfigurationOptions {
    return func(c *Configuration) {
        c.loggerConfiguration = NewLoggerConfiguration(options...)
    }
}

// Environment returns the environment from the Configuration.
func (c Configuration) Environment() Environment {
    return c.environment
}

// HttpConfiguration returns the httpConfiguration from the Configuration.
func (c Configuration) HttpConfiguration() HttpConfiguration {
    return c.httpConfiguration
}

// AuthorizationCodeAuthCredentials returns the authorizationCodeAuthCredentials from the Configuration.
func (c Configuration) AuthorizationCodeAuthCredentials() AuthorizationCodeAuthCredentials {
    return c.authorizationCodeAuthCredentials
}

// CreateConfigurationFromEnvironment creates a new Configuration with default settings.
// It also configures various Configuration options.
func CreateConfigurationFromEnvironment(options ...ConfigurationOptions) Configuration {
    config := DefaultConfiguration()
    
    environment := os.Getenv("E_2_E_LANGUAGE_SELECT_API_ENVIRONMENT")
    if environment != "" {
        config.environment = Environment(environment)
    }
    oAuthClientId := os.Getenv("E_2_E_LANGUAGE_SELECT_API_O_AUTH_CLIENT_ID")
    if oAuthClientId != "" {
        config.authorizationCodeAuthCredentials.oAuthClientId = oAuthClientId
    }
    oAuthClientSecret := os.Getenv("E_2_E_LANGUAGE_SELECT_API_O_AUTH_CLIENT_SECRET")
    if oAuthClientSecret != "" {
        config.authorizationCodeAuthCredentials.oAuthClientSecret = oAuthClientSecret
    }
    oAuthRedirectUri := os.Getenv("E_2_E_LANGUAGE_SELECT_API_O_AUTH_REDIRECT_URI")
    if oAuthRedirectUri != "" {
        config.authorizationCodeAuthCredentials.oAuthRedirectUri = oAuthRedirectUri
    }
    for _, option := range options {
        option(&config)
    }
    return config
}

// Server represents available servers.
type Server string

const (
    EnumDefault Server = "default"
    AuthServer  Server = "auth server"
)

// Environment represents available environments.
type Environment string

const (
    PRODUCTION Environment = "production"
)

// CreateRetryConfiguration creates a new RetryConfiguration with the provided options.
func CreateRetryConfiguration(options ...RetryConfigurationOptions) RetryConfiguration {
    config := DefaultRetryConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// CreateHttpConfiguration creates a new HttpConfiguration with the provided options.
func CreateHttpConfiguration(options ...HttpConfigurationOptions) HttpConfiguration {
    config := DefaultHttpConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// CreateConfiguration creates a new Configuration with the provided options.
func CreateConfiguration(options ...ConfigurationOptions) Configuration {
    config := DefaultConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}
