// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package e2ELanguageSelectApi

import (
    "context"
    "e2ELanguageSelectApi/errors"
    "e2ELanguageSelectApi/models"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
)

// OAuthAuthorizationController represents a controller struct.
type OAuthAuthorizationController struct {
    baseController
}

// NewOAuthAuthorizationController creates a new instance of OAuthAuthorizationController.
// It takes a baseController as a parameter and returns a pointer to the OAuthAuthorizationController.
func NewOAuthAuthorizationController(baseController baseController) *OAuthAuthorizationController {
    oAuthAuthorizationController := OAuthAuthorizationController{baseController: baseController}
    return &oAuthAuthorizationController
}

// RequestTokenInput represents the input of the RequestToken endpoint.
type RequestTokenInput struct {
    // Authorization header in Basic auth format
    Authorization string 
    // Authorization Code
    Code          string 
    // Redirect Uri
    RedirectUri   string 
}

// RequestToken takes context, authorization, code, redirectUri as parameters and
// returns an models.ApiResponse with models.OAuthToken data and
// an error if there was an issue with the request or response.
// Create a new OAuth 2 token.
func (o *OAuthAuthorizationController) RequestToken(
    ctx context.Context,
    input RequestTokenInput,
    formParams map[string]any) (
    models.ApiResponse[models.OAuthToken],
    error) {
    req := o.prepareRequest(ctx, "POST", "/oauth/v1/token")
    
    req.BaseUrl("default")
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "OAuth 2 provider returned an error.", Unmarshaller: errors.NewOAuthProvider},
        "401": {Message: "OAuth 2 provider says client authentication failed.", Unmarshaller: errors.NewOAuthProvider},
    })
    req.Header("Authorization", input.Authorization)
    req.FormParam("grant_type", "authorization_code")
    req.FormParam("code", input.Code)
    req.FormParam("redirect_uri", input.RedirectUri)
    req.FormParams(formParams)
    var result models.OAuthToken
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.OAuthToken](decoder)
    return models.NewApiResponse(result, resp), err
}

// RefreshTokenInput represents the input of the RefreshToken endpoint.
type RefreshTokenInput struct {
    // Authorization header in Basic auth format
    Authorization string  
    // Refresh token
    RefreshToken  string  
    // Requested scopes as a space-delimited list.
    Scope         *string 
}

// RefreshToken takes context, authorization, refreshToken, scope as parameters and
// returns an models.ApiResponse with models.OAuthToken data and
// an error if there was an issue with the request or response.
// Obtain a new access token using a refresh token
func (o *OAuthAuthorizationController) RefreshToken(
    ctx context.Context,
    input RefreshTokenInput,
    formParams map[string]any) (
    models.ApiResponse[models.OAuthToken],
    error) {
    req := o.prepareRequest(ctx, "POST", "/oauth/v1/token")
    
    req.BaseUrl("default")
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "OAuth 2 provider returned an error.", Unmarshaller: errors.NewOAuthProvider},
        "401": {Message: "OAuth 2 provider says client authentication failed.", Unmarshaller: errors.NewOAuthProvider},
    })
    req.Header("Authorization", input.Authorization)
    req.FormParam("grant_type", "refresh_token")
    req.FormParam("refresh_token", input.RefreshToken)
    if input.Scope != nil {
        req.FormParam("scope", *input.Scope)
    }
    req.FormParams(formParams)
    var result models.OAuthToken
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.OAuthToken](decoder)
    return models.NewApiResponse(result, resp), err
}
