// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Contact represents a Contact struct.
type Contact struct {
    Id                   *string                `json:"id,omitempty"`
    Email                *string                `json:"email,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Contact,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c Contact) String() string {
    return fmt.Sprintf(
    	"Contact[Id=%v, Email=%v, AdditionalProperties=%v]",
    	c.Id, c.Email, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Contact.
// It customizes the JSON marshaling process for Contact objects.
func (c Contact) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "id", "email"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the Contact object to a map representation for JSON marshaling.
func (c Contact) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.Id != nil {
        structMap["id"] = c.Id
    }
    if c.Email != nil {
        structMap["email"] = c.Email
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Contact.
// It customizes the JSON unmarshaling process for Contact objects.
func (c *Contact) UnmarshalJSON(input []byte) error {
    var temp tempContact
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id", "email")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Id = temp.Id
    c.Email = temp.Email
    return nil
}

// tempContact is a temporary struct used for validating the fields of Contact.
type tempContact  struct {
    Id    *string `json:"id,omitempty"`
    Email *string `json:"email,omitempty"`
}
