// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// CrmV3ObjectsContactsResponse represents a CrmV3ObjectsContactsResponse struct.
type CrmV3ObjectsContactsResponse struct {
    Results              []Contact              `json:"results,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CrmV3ObjectsContactsResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CrmV3ObjectsContactsResponse) String() string {
    return fmt.Sprintf(
    	"CrmV3ObjectsContactsResponse[Results=%v, AdditionalProperties=%v]",
    	c.Results, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CrmV3ObjectsContactsResponse.
// It customizes the JSON marshaling process for CrmV3ObjectsContactsResponse objects.
func (c CrmV3ObjectsContactsResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "results"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CrmV3ObjectsContactsResponse object to a map representation for JSON marshaling.
func (c CrmV3ObjectsContactsResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.Results != nil {
        structMap["results"] = c.Results
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CrmV3ObjectsContactsResponse.
// It customizes the JSON unmarshaling process for CrmV3ObjectsContactsResponse objects.
func (c *CrmV3ObjectsContactsResponse) UnmarshalJSON(input []byte) error {
    var temp tempCrmV3ObjectsContactsResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "results")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Results = temp.Results
    return nil
}

// tempCrmV3ObjectsContactsResponse is a temporary struct used for validating the fields of CrmV3ObjectsContactsResponse.
type tempCrmV3ObjectsContactsResponse  struct {
    Results []Contact `json:"results,omitempty"`
}
