// Package e2ELanguageSelectApi
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// OAuthProviderError is a string enum.
// OAuth 2 Authorization error codes
type OAuthProviderError string

// MarshalJSON implements the json.Marshaler interface for OAuthProviderError.
// It customizes the JSON marshaling process for OAuthProviderError objects.
func (e OAuthProviderError) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for OAuthProviderError")
}

// UnmarshalJSON implements the json.Unmarshaler interface for OAuthProviderError.
// It customizes the JSON unmarshaling process for OAuthProviderError objects.
func (e *OAuthProviderError) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = OAuthProviderError(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to OAuthProviderError")
    }
    return nil
}

// Checks whether the value is actually a member of OAuthProviderError.
func (e OAuthProviderError) isValid() bool {
    switch e {
    case OAuthProviderError_InvalidRequest,
        OAuthProviderError_InvalidClient,
        OAuthProviderError_InvalidGrant,
        OAuthProviderError_UnauthorizedClient,
        OAuthProviderError_UnsupportedGrantType,
        OAuthProviderError_InvalidScope:
        return true
    }
    return false
}

const (
    OAuthProviderError_InvalidRequest       OAuthProviderError = "invalid_request"
    OAuthProviderError_InvalidClient        OAuthProviderError = "invalid_client"
    OAuthProviderError_InvalidGrant         OAuthProviderError = "invalid_grant"
    OAuthProviderError_UnauthorizedClient   OAuthProviderError = "unauthorized_client"
    OAuthProviderError_UnsupportedGrantType OAuthProviderError = "unsupported_grant_type"
    OAuthProviderError_InvalidScope         OAuthProviderError = "invalid_scope"
)

// OAuthScope is a string enum.
// OAuth 2 scopes supported by the API
type OAuthScope string

// MarshalJSON implements the json.Marshaler interface for OAuthScope.
// It customizes the JSON marshaling process for OAuthScope objects.
func (e OAuthScope) MarshalJSON() (
    []byte,
    error) {
    if e.isValid() {
        return []byte(fmt.Sprintf("\"%v\"", e)), nil
    }
    return nil, errors.New("the provided enum value is not allowed for OAuthScope")
}

// UnmarshalJSON implements the json.Unmarshaler interface for OAuthScope.
// It customizes the JSON unmarshaling process for OAuthScope objects.
func (e *OAuthScope) UnmarshalJSON(input []byte) error {
    var enumValue string
    err := json.Unmarshal(input, &enumValue)
    if err != nil {
        return err
    }
    *e = OAuthScope(enumValue)
    if !e.isValid() {
        return errors.New("the value " + string(input) + " cannot be unmarshalled to OAuthScope")
    }
    return nil
}

// Checks whether the value is actually a member of OAuthScope.
func (e OAuthScope) isValid() bool {
    switch e {
    case OAuthScope_CrmObjectsContactsRead:
        return true
    }
    return false
}

const (
    OAuthScope_CrmObjectsContactsRead OAuthScope = "crm.objects.contacts.read"
)
